name: Build Ghostty

on:
  workflow_dispatch:

jobs:
  build-ghostty:
    name: Build Ghostty
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.10
    steps:
      - name: Checkout ghostty-ubuntu
        uses: actions/checkout@v4
      
      - name: Build Ghostty
        run: ./build-ghostty.sh
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ghostty_*.deb
        