name: Build Ghostty

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: If empty, rest with build artifact. If nonempty, release that version.
        type: string
        required: false

permissions:
  contents: write

jobs:
  build-ghostty:
    name: Build Ghostty
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.10
    steps:
      - name: Checkout ghostty-ubuntu
        uses: actions/checkout@v4
      
      - name: Build Ghostty
        run: ./build-ghostty.sh
      
      - name: Upload Artifact
        if: inputs.release_version == ''
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ghostty_*.deb
      
      - name: Create Release
        if: inputs.release_version != ''
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ghostty_*.deb
          tag_name: ${{ inputs.release_version }}
          fail_on_unmatched_files: true
        