name: Build Ghostty

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_version:
        description: If empty, rest with build artifact. If nonempty, release that version.
        type: string
        required: false

permissions:
  contents: write

jobs:
  build-ghostty:
    name: Build Ghostty
    strategy:
      matrix:
        ubuntu_version: [22.04, 24.04, 24.10]
    runs-on: ubuntu-latest
    container:
      image: ubuntu:${{ matrix.ubuntu_version }}
    steps:
      - name: Checkout ghostty-ubuntu
        uses: actions/checkout@v4
      
      - name: Build Ghostty
        run: ./build-ghostty.sh
      
      - name: Upload Artifact
        if: inputs.release_version == ''
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.ubuntu_version }}
          path: ghostty_*.deb
        